server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/user_leave_tracking?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database: mysql
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:create-drop}
  jackson:
    serialization:
      indent-output: true
  liquibase:
    change-log: classpath:liquibase/changelog-master.xml
    enabled: true

logging:
  level:
    liquibase: INFO